name: serverpod_playground_flutter
description: A new Flutter project with Serverpod.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  serverpod_flutter: 2.1.5
  serverpod_playground_client:
    path: ../serverpod_playground_client
  cupertino_icons: ^1.0.8
  bloc: ^8.1.4
  equatable: ^2.0.5
  go_router: ^14.3.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  logging: ^1.3.0
  flutter_bloc: ^8.1.6
  flutter_form_builder: ^9.5.0
  flutter_native_splash: ^2.4.2
  serverpod_auth_email_flutter: 2.1.5
  serverpod_auth_shared_flutter: 2.1.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  test: ^1.25.7
  intl_utils: ^2.8.7

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash_screen.png

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_intl:
  enabled: true
  output_dir: lib/l10n/generated
